#version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15
    container_name: simple-list-db
    environment:
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_password
      POSTGRES_DB: simple_list_db
      DATABASE_URL: "postgresql://simple_user:simple_password@db:5432/simple_list_db"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simple_user -d simple_list_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Бэкенд Python
  backend:
    build: ./backend
    container_name: simple-list-backend
    environment:
      DATABASE_URL: postgresql://simple_user:simple_password@db:5432/simple_list_db
    ports:
      - "8080:8000" # внешний : внутренний 

    volumes:
        - ./backend:/app  # для быстрой отладки

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Фронтенд Nginx
  frontend:
    build: ./frontend
    container_name: simple-list-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

    volumes:
    - ./frontend:/usr/share/nginx/html  # для быстрой отладки: Правим файлы в папке frontend/, изменения сразу появятся в контейнере (F5)

volumes:
  postgres_data: